
DROP TABLE IF EXISTS `WORKFLOW_BUSINESS`;
CREATE TABLE `WORKFLOW_BUSINESS` (
  `BUSINESS_ID` varchar(64) NOT NULL COMMENT '唯一主键业务ID',
  `TITLE` varchar(64) NOT NULL COMMENT '流程申请名称',
  `BUSINESS_TYPE` int(2) NOT NULL COMMENT '功能类型',
  `FUNCTION_IDS` varchar(255) NOT NULL COMMENT '申请功能IDs，多个使用逗号分隔',
  `REASON` text COMMENT '申请原因',
  `PROCESS_ID` varchar(64) NOT NULL COMMENT '流程实例ID',
  `USER_ID` varchar(64) NOT NULL COMMENT '申请流程的用户ID',
  `STATUS` int(2) NOT NULL DEFAULT '0' COMMENT '流程状态，0审核中，1通过，2不通过',
  `CREATE_BY` varchar(255) NOT NULL COMMENT '创建人',
  `UPDATE_BY` varchar(255) DEFAULT NULL COMMENT '更新人',
  `CREATE_TIME` datetime(3) DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime(3) DEFAULT NULL COMMENT '更新时间',
  `REMARK` varchar(255) DEFAULT NULL COMMENT '备注',
  `ATTACHMENT` varchar(255) DEFAULT NULL COMMENT '附件',
  `PRESENT_BY` varchar(125) DEFAULT NULL COMMENT '当前处理人',
  PRIMARY KEY (`BUSINESS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='功能流程申请业务表';

